# Generated by Django 4.2.21 on 2025-05-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('truck', 'Грузовик'), ('dump_truck', 'Самосвал'), ('loader', 'Погрузчик')], max_length=20)),
                ('estimated_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_info', models.CharField(blank=True, max_length=200)),
                ('tracking_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
